language: go

go:
  - "1.10"
# skip "go get -t ./..." since all dependencies are vendored    
install: true 
script: ./build.sh --nobin
after_success:
  # upload code coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash) -s build/coverage/
